# Generated by Django 5.0.3 on 2024-03-18 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_recommendation_shoppingcart_remove_perfume_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('cellphoneNumber', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='userID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.user'),
        ),
    ]
