# Generated by Django 5.0.3 on 2024-03-18 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_user_delete_recommendation_alter_shoppingcart_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.user')),
                ('purchaseHistory', models.JSONField(blank=True, default=list)),
                ('browsingHistory', models.JSONField(blank=True, default=list)),
                ('recommendationList', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='savedForLater',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
