# Generated by Django 5.0.3 on 2024-03-18 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_shoppingcart_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='items',
        ),
        migrations.AlterField(
            model_name='perfume',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderStatus', models.CharField(max_length=50)),
                ('shippingDetails', models.JSONField()),
                ('orderDate', models.DateField(auto_now_add=True)),
                ('orderHistory', models.JSONField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.perfume')),
            ],
        ),
    ]
