# Generated by Django 5.0.3 on 2024-03-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userProfile', models.CharField(max_length=100)),
                ('purchaseHistory', models.CharField(max_length=100)),
                ('browsingHistory', models.CharField(max_length=100)),
                ('recommendationList', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('userID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('items', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('subtotal', models.CharField(max_length=100)),
                ('savedForLater', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='id',
        ),
        migrations.AlterField(
            model_name='perfume',
            name='productID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
