# Generated by Django 5.0.2 on 2024-03-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
